name: GCC Builds
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [23]
        build_type: ["Release", "Debug"]
        configuration: [
          {"UBUNTU_VERSION":"22.04", "TOOLCHAIN_VERSION":"13"},
          {"UBUNTU_VERSION":"24.04", "TOOLCHAIN_VERSION":"13"}
        ]

    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{matrix.configuration.UBUNTU_VERSION}}

    steps:
      - name: Install system dependencies before checkout
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt-get install -y \
            software-properties-common ca-certificates \
            ninja-build make \
            zlib1g-dev wget zip

          add-apt-repository ppa:git-core/ppa
          apt update && apt install -y git
          git --version

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
#          set-safe-directory: ''

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: lukka/get-cmake@latest  # <--= Just this one-liner suffices.

      - name: Install system dependencies after checkout
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          add-apt-repository ppa:ubuntu-toolchain-r/test

          python3 -m pip install --no-cache-dir --break-system-packages conan==1.63
          conan --version

      - name: Install compiler
        run: |
          apt update && apt-get install -y gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.configuration.TOOLCHAIN_VERSION}} 90 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-${{matrix.configuration.TOOLCHAIN_VERSION}} \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-${{matrix.configuration.TOOLCHAIN_VERSION}}

          update-alternatives --config gcc

      - name: Configure CMake
        env:
          CC: gcc-${{matrix.configuration.TOOLCHAIN_VERSION}}
          CXX: g++-${{matrix.configuration.TOOLCHAIN_VERSION}}
          BUILD_TYPE: ${{matrix.build_type}}
          CXX_STANDARD: ${{matrix.cxx_standard}}
        run: |
          mkdir -p local_build

          conan profile new default --detect --force
          conan profile update settings.arch=x86_64 default
          conan profile update settings.arch_build=x86_64 default
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.version=${{matrix.configuration.TOOLCHAIN_VERSION}} default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update settings.build_type=${BUILD_TYPE} default
          conan profile update env.CXX=${CXX} default
          conan profile update env.CC=${CC} default

          conan install ./conanfile.txt \
          -s:b build_type=${BUILD_TYPE} \
          -s:h build_type=${BUILD_TYPE} \
          --output-folder=local_build \
          --install-folder=local_build \
          --generator CMakeToolchain \
          --build=missing \
          -c:b tools.cmake.cmaketoolchain:generator=Ninja \
          -c:h tools.cmake.cmaketoolchain:generator=Ninja

          cmake -B local_build -GNinja \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DCMAKE_CXX_STANDARD=${CXX_STANDARD} \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_CXX_COMPILER=${CXX} \
            -DCMAKE_TOOLCHAIN_FILE=local_build/build/${BUILD_TYPE}/generators/conan_toolchain.cmake \
            -DWITH_SANITIZER=OFF

      - name: Build
        run: cmake --build local_build

      - name: Test
        working-directory: local_build
        run: ctest --rerun-failed --output-on-failure
